name: Build
run-name: Building docker container.
on:
  push:
    branches: stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update Package Repository.
        run: apt update -y
      - name: Gather dependencies.
        run: apt install -y docker.io
      - name: Check repository out.
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t quik/docker-cross-compiler .